// AUTO-GENERATED by scripts/fetch-social-previews.mjs — do not edit by hand.
// Maps a lowercased repo name to its uploaded GitHub social-preview image URL.
// Regenerated on every build (npm run prebuild). Repos without a custom preview are
// omitted; the app falls back to GitHub's generated graph card for those.

export const SOCIAL_PREVIEWS: Record<string, string> = {
  "denguerisk": "https://repository-images.githubusercontent.com/1179074622/29e5b9d1-125a-41a8-97c2-28b88cb7a99f",
  "discord_music_bot": "https://repository-images.githubusercontent.com/1111201356/c97a3b09-2120-4148-b682-4cf1b5d8427b",
  "discord-j4fn-server-bot": "https://repository-images.githubusercontent.com/1101810861/81d473c6-818c-4b83-9f94-344aa7bc6b62",
  "discord-youtube-status-bot": "https://repository-images.githubusercontent.com/1246466961/27512341-f653-40e8-be94-04e6dbb8135f",
  "home-tutor": "https://repository-images.githubusercontent.com/1249950903/c3c387dc-44a7-4b82-8724-ae922b902cbc",
  "just-for-fun-website": "https://repository-images.githubusercontent.com/1101865931/1d62c29a-d8c7-4869-84dd-756c372b2c07",
  "kavisha_portfolio": "https://repository-images.githubusercontent.com/1133475431/2b60a04b-c065-4002-804b-4e9149ebb684",
  "kavisha_portfolio-v2": "https://repository-images.githubusercontent.com/1276894842/bb7b4bf3-c065-4692-84f2-520186cd3fa8",
  "stremio_discord_rich_presence": "https://repository-images.githubusercontent.com/1258308482/5e5f4667-39b8-42a9-b39a-498e56bd0fa5",
  "travel_genie": "https://repository-images.githubusercontent.com/1219954621/614682d9-723c-4ef7-8402-4e198faef8b4",
  "travel_genie_app": "https://repository-images.githubusercontent.com/1240803395/d312e254-6820-4551-a7c9-b9d4fbb2a8d8",
  "web-voting-system": "https://repository-images.githubusercontent.com/1179071882/d7aefbd2-d7ce-445e-9fac-26e4bf245d6b"
};
