// AUTO-GENERATED by scripts/fetch-social-previews.mjs — do not edit by hand.
// Metadata is resolved outside the browser so client loads need only one public API request.

export const SOCIAL_PREVIEWS: Record<string, string> = {
  "denguerisk": "https://repository-images.githubusercontent.com/1179074622/29e5b9d1-125a-41a8-97c2-28b88cb7a99f",
  "discord_music_bot": "https://repository-images.githubusercontent.com/1111201356/c97a3b09-2120-4148-b682-4cf1b5d8427b",
  "discord-j4fn-server-bot": "https://repository-images.githubusercontent.com/1101810861/81d473c6-818c-4b83-9f94-344aa7bc6b62",
  "discord-youtube-status-bot": "https://repository-images.githubusercontent.com/1246466961/27512341-f653-40e8-be94-04e6dbb8135f",
  "home-tutor": "https://repository-images.githubusercontent.com/1249950903/c3c387dc-44a7-4b82-8724-ae922b902cbc",
  "job-hunting-tracker": "https://repository-images.githubusercontent.com/1327400924/f2716e23-a010-4a0b-b543-212df1362542",
  "just-for-fun-website": "https://repository-images.githubusercontent.com/1101865931/1d62c29a-d8c7-4869-84dd-756c372b2c07",
  "kavisha_portfolio": "https://repository-images.githubusercontent.com/1133475431/2b60a04b-c065-4002-804b-4e9149ebb684",
  "kavisha_portfolio-v2": "https://repository-images.githubusercontent.com/1276894842/bb7b4bf3-c065-4692-84f2-520186cd3fa8",
  "mazora-network": "https://repository-images.githubusercontent.com/1297488187/e199c727-2daa-4923-bfef-71b855851ab3",
  "salon_vero_app": "https://repository-images.githubusercontent.com/1264174720/7d262a4b-9cea-4372-9e5b-0c05f1c36fc5",
  "stremio_discord_rich_presence": "https://repository-images.githubusercontent.com/1258308482/5e5f4667-39b8-42a9-b39a-498e56bd0fa5",
  "travel_genie": "https://repository-images.githubusercontent.com/1219954621/614682d9-723c-4ef7-8402-4e198faef8b4",
  "travel_genie_app": "https://repository-images.githubusercontent.com/1240803395/d312e254-6820-4551-a7c9-b9d4fbb2a8d8",
  "vero_salon_website": "https://repository-images.githubusercontent.com/1276927785/7f8ef0a6-3961-4ba7-b3a2-ec4390fcaf33",
  "web-voting-system": "https://repository-images.githubusercontent.com/1179071882/d7aefbd2-d7ce-445e-9fac-26e4bf245d6b"
};

export const PROJECT_METADATA: Record<string, {
  allLanguages: string[];
  latestRelease?: { version: string; url: string; downloads: number } | null;
}> = {
  "denguerisk": {
    "allLanguages": [
      "Jupyter Notebook",
      "HTML",
      "CSS",
      "JavaScript"
    ],
    "latestRelease": null
  },
  "discord_music_bot": {
    "allLanguages": [
      "JavaScript",
      "CSS",
      "HTML",
      "Dockerfile"
    ],
    "latestRelease": null
  },
  "discord-j4fn-server-bot": {
    "allLanguages": [
      "Python",
      "HTML",
      "CSS",
      "JavaScript",
      "Dockerfile"
    ],
    "latestRelease": null
  },
  "discord-youtube-status-bot": {
    "allLanguages": [
      "HTML",
      "Python",
      "Dockerfile"
    ],
    "latestRelease": null
  },
  "home-tutor": {
    "allLanguages": [
      "Java"
    ],
    "latestRelease": null
  },
  "it3012---it24101927": {
    "allLanguages": [],
    "latestRelease": null
  },
  "job-hunting-tracker": {
    "allLanguages": [
      "JavaScript",
      "HTML",
      "CSS"
    ],
    "latestRelease": null
  },
  "just-for-fun-website": {
    "allLanguages": [
      "TypeScript",
      "CSS",
      "JavaScript"
    ],
    "latestRelease": null
  },
  "kavisha_portfolio": {
    "allLanguages": [
      "CSS",
      "HTML",
      "JavaScript"
    ],
    "latestRelease": null
  },
  "kavisha_portfolio-v2": {
    "allLanguages": [
      "TypeScript",
      "JavaScript",
      "CSS",
      "HTML"
    ],
    "latestRelease": null
  },
  "macromaster101": {
    "allLanguages": [
      "JavaScript"
    ],
    "latestRelease": null
  },
  "mazora-network": {
    "allLanguages": [
      "TypeScript",
      "CSS",
      "PLpgSQL",
      "JavaScript"
    ],
    "latestRelease": null
  },
  "salon_vero_app": {
    "allLanguages": [
      "TypeScript",
      "JavaScript"
    ],
    "latestRelease": null
  },
  "stremio_discord_rich_presence": {
    "allLanguages": [
      "JavaScript",
      "HTML",
      "NSIS"
    ],
    "latestRelease": {
      "version": "v1.0.11",
      "url": "https://github.com/MacroMaster101/Stremio_Discord_Rich_Presence/releases/download/v1.0.11/Stremio-Discord-Presence-Setup-1.0.11.exe",
      "downloads": 12
    }
  },
  "thilak_products_website": {
    "allLanguages": [
      "TypeScript",
      "CSS",
      "JavaScript"
    ],
    "latestRelease": null
  },
  "travel_genie": {
    "allLanguages": [
      "JavaScript",
      "CSS",
      "Python",
      "HTML",
      "Procfile"
    ],
    "latestRelease": null
  },
  "travel_genie_app": {
    "allLanguages": [
      "JavaScript"
    ],
    "latestRelease": null
  },
  "vero_salon_website": {
    "allLanguages": [
      "TypeScript",
      "CSS",
      "PLpgSQL",
      "JavaScript"
    ],
    "latestRelease": null
  },
  "web-voting-system": {
    "allLanguages": [
      "JavaScript",
      "CSS",
      "Java",
      "HTML"
    ],
    "latestRelease": null
  },
  "weekly-report-dashboard": {
    "allLanguages": [
      "TypeScript",
      "CSS",
      "JavaScript"
    ],
    "latestRelease": null
  }
};
